project:
  type: website
  output-dir: docs

website:
  title: "ddunn303.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: 
      - yeti
      - brand
    
    css: styles.css
    toc: false
    page-layout: full
    

editor: visual

